# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV.fetch("DB_USER")%>
  password: <%= ENV.fetch("DB_PASSWORD")%>
  host: <%= ENV.fetch("DB_HOST")%>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"]%>
  database: railwayapp_production
  username: railwayapp
  password: <%= ENV["RAILWAYAPP_DATABASE_PASSWORD"]%>


test:
  <<: *default
  database: store_api_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"]%>
  database: railwayapp_production
  username: railwayapp
  password: <%= ENV["RAILWAYAPP_DATABASE_PASSWORD"]%>

