# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV.fetch("DB_USER")%>
  password: <%= ENV.fetch("DB_PASSWORD")%>
  host: <%= ENV.fetch("DB_HOST")%>

development:
  <<: *default
  database: store_api_development
  user: <%= ENV.fetch("DB_USER_PROD")%>
  password: <%= ENV.fetch("DB_PASSWORD_PROD")%>
  host: <%= ENV.fetch("DB_HOST_PROD")%>

test:
  <<: *default
  database: store_api_test

production:
  <<: *default
  database: store_api_production
  user: <%= ENV.fetch("DB_USER_PROD")%>
  password: <%= ENV.fetch("DB_PASSWORD_PROD")%>
  host: <%= ENV.fetch("DB_HOST_PROD")%>
